apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: product
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: manassesalmeida/docker-sample-project-backend:1.0
        ports:
        - containerPort: 8080
  replicas: 1