apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: product
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: manassesalmeida/docker-sample-project-frontend:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
  replicas: 1