apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: product
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
