apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: product
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: "backend"
    port: 8080
    targetPort: 8080
    nodePort: 31000