apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: product
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 3306
    targetPort: 3306
    name: "database-service"
