apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: product
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: "frontend"
    port: 80
    targetPort: 80
    nodePort: 31001